atasnap:
  prefix_exec: /home/sonata/src/hashpipe/src/
  prefix_lib: /home/sonata/src/hpguppi_daq/src/.libs/
  # hpguppi_plugin:
  logdir: /home/sonata/logs
  # command_prefix:
  setup_commands:
    - 16: 
        - ethtool -L $BINDHOST combined 32
        - [
          "set_irq_affinity_cpulist.sh 14,15 $BINDHOST",
          "set_irq_affinity_cpulist.sh 30,31 $BINDHOST",
        ]
        - cpupower -c 0-31 idle-set -d 2
      24:
        - ethtool -L $BINDHOST combined 48
        - [
          "set_irq_affinity_cpulist.sh 22,23 $BINDHOST",
          "set_irq_affinity_cpulist.sh 46,47 $BINDHOST",
        ]
        - cpupower -c 0-47 idle-set -d 2
    - ethtool -C $BINDHOST adaptive-rx on rx-frames 8 rx-usecs 0
    - ethtool -G $BINDHOST rx 8192
    - cpupower frequency-set -g performance
    - /opt/mnt/bin/kill_redis_gateway.sh $INSTANCE
  post_commands:
    - sleep 2
    - /opt/mnt/bin/init_redis_gateway.sh $INSTANCE
  hashpipe_keyfile: /home/sonata
  environment:
    - ATASHAREDIR="/opt/mnt"
    - rvm_bin_path=/home/sonata/.rvm/bin
    - GEM_PATH=/home/sonata/.rvm/gems/ruby-2.1.10:/home/sonata/.rvm/gems/ruby-2.1.10@global
    - GEM_HOME=/home/sonata/.rvm/gems/ruby-2.1.10
    - LD_LIBRARY_PATH=/home/sonata/src/hashpipe/src/.libs:/opt/mnt/lib
    - PATH=/opt/mnt/bin:$PATH:/home/sonata/.rvm/rubies/ruby-2.1.10/bin:/home/sonata/.rvm/bin:/home/sonata/.rvm/gems/ruby-2.1.10/bin
  options:
    # - IBVPKTSZ=42,16,8208
    - IBVPKTSZ=42,16,4112
    - BINDPORT=10000
  instance_numanode_bind: [0, 1]
  instance_datadir: [/mnt/buf0, /mnt/buf1]
  instance_bindhost: [enp97s0f1, enp225s0f1]
  thread_mask_lengths:
    hpguppi_atasnap_pkt_to_FTP_transpose:
      6
    hpguppi_atasnap_ibv_voltage_only_thread:
      6
    hpguppi_atasnap_ibv_voltage_ftp_thread:
      8
  subsystem_threads:
    ibv:
      - hpguppi_ibvpkt_thread
      - hpguppi_atasnap_ibv_voltage_ftp_thread
      - hpguppi_atasnap_obs_rawdisk_thread
    ibv_optimised_old: # These threads aren't compiled any-longer
      - hpguppi_ibvpkt_thread
      - hpguppi_atasnap_ibv_voltage_only_thread
      - hpguppi_atasnap_pkt_to_FTP_transpose
      - hpguppi_atasnap_control_thread
      - hpguppi_atasnap_rawdisk_thread
  cpu_core_count_config:
    16:
      instance_cpu_core_0: [1, 17]
    24:
      instance_cpu_core_0: [1, 25]

##################### Templates #####################
template_singular: # Singular System Configuration Definition
  # prefix_exec: /opt/mnt/bin/ # The directory for the hashpipe executable
  # prefix_lib: /opt/mnt/lib/ # The directory for the hpguppi_daq.so 
  # hpguppi_plugin: hpguppi_daq.so # The name of the hpguppi_daq plugin
  # logdir: # The directory to log to (if missing, no logging takes place)
  # command_prefix: # Commands to insert before `hashpipe` in the final command
  # setup_commands: # List of commands to run before starting the instance
  # post_commands: # List of commands to run after having started the instance
  # hashpipe_keyfile: # The value of the instance's HASHPIPE_KEYFILE environment variable
  # environment: # List of key=value environment variables for the instance
  # options: # List of status-buffer key=value options for the command (each prefixed with -o)
  # instance_numanode_bind: # $instance indexed list of numanode numbers to cpu/mem-bind the instance to (if missing numanode $instance is bound to)
  instance_datadir: # $instance indexed list of DATADIR values to set for the instance
    - /mnt/buf0
    - /mnt/buf1
  instance_bindhost: # $instance indexed list of DATADIR values to set for the instance
    - enp97s0f1
    - enp225s0f1
  # thread_mask_lengths: # thread_name=mask_length map of mask lengths for threads (otherwise assumed to be 1 (single-core threads))
  threads: # Sequential list of threads for an instance of the system
  cpu_core_count_config: [] # Either a simple list of core_counts supported 
  ########################### or
  # cpu_core_count_config:  # A core_count={} map of further configuration specifications
    # 16:
      # instance_cpu_core_0: # $instance indexed list of cpu_cores from which to start thread masking
      # instance_thread_masks: # thread=[instance_mask_list] map to $instance indexed lists of thread-masks (a thread-mask that is a list is possible for multi-core threads)
template_sub-multitudinous: # Mulitple Sub-System Configuration Definitions
  # prefix_exec: /opt/mnt/bin/ # The directory for the hashpipe executable
  # prefix_lib: /opt/mnt/lib/ # The directory for the hpguppi_daq.so 
  # hpguppi_plugin: hpguppi_daq.so # The name of the hpguppi_daq plugin
  # logdir: # The directory to log to (if missing, no logging takes place)
  # command_prefix: # Commands to insert before `hashpipe` in the final command
  # setup_commands: # List of commands to run before starting the instance
  # post_commands: # List of commands to run after having started the instance
  # hashpipe_keyfile: # The value of the instance's HASHPIPE_KEYFILE environment variable
  # environment: # List of key=value environment variables for the instance
  # options: # List of status-buffer key=value options for the command (each prefixed with -o)
  # instance_numanode_bind: # $instance indexed list of numanode numbers to cpu/mem-bind the instance to (if missing numanode $instance is bound to)
  instance_datadir: # $instance indexed list of DATADIR values to set for the instance
    - /mnt/buf0
    - /mnt/buf1
  instance_bindhost: # $instance indexed list of DATADIR values to set for the instance
    - enp97s0f1
    - enp225s0f1
  # thread_mask_lengths: # thread_name=mask_length map of mask lengths for threads (otherwise assumed to be 1 (single-core threads))
  subsystem_threads: # subsystem=[threads_list] map to
    $subsystem: # Sequential list of threads for an instance of the subsystem
  cpu_core_count_config: [] # Either a simple list of core_counts supported 
  ########################### or
  # cpu_core_count_config:  # A core_count={} map of further configuration specifications
    # 16:
      # instance_cpu_core_0: # $instance indexed list of cpu_cores from which to start thread masking
      # instance_subsystem_thread_masks: # subsystem={thread=[instance_mask_list]} map of thread maps 
        # $thread_name: to $instance indexed lists of thread-masks (a thread-mask that is a list is possible for multi-core threads)